train:
  get_spectrogram:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
    n_mels: 128
  audio:
    _target_: torchvision.transforms.v2.Compose
    transforms:
    - _target_: src.transforms.wav_augs.Gain
    - _target_: src.transforms.wav_augs.WhiteNoise
      min_snr_db: 15
      max_snr_db: 35
    - _target_: src.transforms.wav_augs.PitchShift
      sample_rate: 16000
      n_steps_range: [ -2, 2 ]
inference:
  get_spectrogram:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
    n_mels: 128
