train:
  get_spectrogram: null # Убираем отсюда
  audio:
    _target_: torchvision.transforms.v2.Compose
    transforms:
    - _target_: src.transforms.wav_augs.Gain
    - _target_: src.transforms.wav_augs.WhiteNoise
      min_snr_db: 15
      max_snr_db: 35
inference:
  get_spectrogram: null # Убираем отсюда